---
title: "bb-cartogram-tract"
output: html_document
---

```{r}

library(dplyr)
library(cori.charts)
library(ggplot2)
library(scales)
library(classInt)
library(cartogram)

library(sysfonts)
library(showtext)

sysfonts::font_add_google("Lato")
font_add(
  "TT Hoves",
  regular = "TypeType - TT Hoves Regular.ttf",
  bold = "TypeType - TT Hoves Bold.ttf",
  italic = "TypeType - TT Hoves Italic.ttf",
  bolditalic = "TypeType - TT Hoves Bold Italic.ttf"
)
showtext_auto()
showtext_opts(dpi = 300)

here::i_am("R/bb-cartogram-tract.Rmd")
source(here::here("R/utils.R"))

```

```{r}

bb_co <- get_bb_co(geo = TRUE) %>%
  filter(!is.na(cnt_25_3_loc)) %>%
  filter(STATEFP == "08") %>%
  sf::st_as_sf()

# construct cartogram
bb_co_cart <- cartogram_cont(bb_co, "cnt_25_3_loc", itermax = 5)

```


```{r}

fig <- bb_co_cart %>%
  ggplot() +
  geom_sf(aes(fill = pct_25_3_loc), color = "#d0d2ce", linewidth = 0.01) +
  scale_fill_gradient2(
    low = "#f7fbff", mid = "#6baed6", midpoint = 0.5, high = "#08306b", na.value = "#d0d2ce",
    labels = scales::percent_format(scale = 100)
  ) +
  theme_cori_map() +
  theme(
    legend.key.width = unit(30, "pt"),
    legend.margin = margin(t = 5)
  ) +
  labs(
    title = "Cartogram",
    subtitle = "Percent of locations with 25/3 broadband service",
    caption = "Source: 2022 FCC estimates"
  )

fig

```


