---
title: "bb-dot-density"
output: html_document
---


```{r}

library(dplyr)
library(cori.charts)
library(ggplot2)
library(scales)
library(classInt)
library(ggmap)
library(sf)

library(sysfonts)
library(showtext)

sysfonts::font_add_google("Lato")
font_add(
  "TT Hoves",
  regular = "TypeType - TT Hoves Regular.ttf",
  bold = "TypeType - TT Hoves Bold.ttf",
  italic = "TypeType - TT Hoves Italic.ttf",
  bolditalic = "TypeType - TT Hoves Bold Italic.ttf"
)
showtext_auto()
showtext_opts(dpi = 300)

here::i_am("R/bb-dot-density.Rmd")
source(here::here("R/utils.R"))

```


```{r}

bb_tr <- get_bb_tr(geo = TRUE, st = "08")

```


```{r}

tracts <- tigris::tracts(state = "08", cb = TRUE, year = 2021) %>%
  sf::st_as_sf() %>%
  sf::st_transform(crs = sf::st_crs(3857))

counties <- tigris::counties(state = "08", cb = TRUE, year = 2021) %>%
  sf::st_as_sf() %>%
  sf::st_transform(crs = sf::st_crs(3857))

unserved_dots <- bb_tr %>%
  mutate(
    cnt_unserved = cnt_total_locations - cnt_100_20
  ) %>%
  filter(!is.na(cnt_unserved)) %>%
  filter(cnt_unserved > 0) %>%
  sf::st_as_sf() %>%
  tidycensus::as_dot_density(
    "cnt_unserved",
    100
  ) %>%
  mutate(
    service_level = "Unserved"
  ) %>%
  sf::st_as_sf() %>%
  sf::st_transform(crs = sf::st_crs(3857))

```

```{r}

served_dots <- bb_tr %>%
  filter(!is.na(cnt_100_20)) %>%
  filter(cnt_100_20 > 0) %>%
  sf::st_as_sf() %>%
  tidycensus::as_dot_density(
    "cnt_100_20",
    100
  ) %>%
  mutate(
    service_level = "Served"
  ) %>%
  sf::st_as_sf() %>%
  sf::st_transform(crs = sf::st_crs(3857))

```


```{r}

dots <- bind_rows(
    unserved_dots,
    served_dots
  ) %>%
  slice(sample(n()))

```


```{r}

fig <- ggplot() +
  geom_sf(data = counties, linewidth = .1, fill = "#FFFFF9", color = "dimgray") +
  geom_sf(data = dots, aes(color = service_level), size = .2, alpha = .6) +
  theme_cori_map_presentation() +
  scale_color_manual(values = c("Served" = "#65ACA5", "Unserved" = "#BA578C")) +
  labs(
    title = "Broadband access in Colorado",
    subtitle = "One dot equals 50 broadband serviceable locations",
    caption = "Source: 2022 FCC estimates\nNotes: Dots are randomly placed within tracts. Served locations have greater than\n100/20 Mbps broadband service."
  ) +
  theme(
    legend.margin = margin(t = 15)
  ) +
  guides(
    color = guide_legend(
      override.aes = list(
        size = 4,
        alpha = 1
      )
    )
  )

save_plot(fig, here::here("export/bb_dot_density_tract.png"), chart_height = 8.8)

```