---
title: "choropleth"
output: html_document
---

```{r}

library(dplyr)
library(cori.charts)
library(ggplot2)
library(scales)
library(classInt)

library(sysfonts)
library(showtext)

sysfonts::font_add_google("Lato")
font_add(
  "TT Hoves",
  regular = "TypeType - TT Hoves Regular.ttf",
  bold = "TypeType - TT Hoves Bold.ttf",
  italic = "TypeType - TT Hoves Italic.ttf",
  bolditalic = "TypeType - TT Hoves Bold Italic.ttf"
)
showtext_auto()
showtext_opts(dpi = 300)

here::i_am("R/choropleth.Rmd")
source(here::here("R/utils.R"))

```


```{r}

bb_co <- get_bb_co(geo = TRUE)


```


```{r}

chrt_dta <- bb_co %>%
  filter(STUSPS == "CO") %>%
  # mutate(pct_25_3_loc = scales::percent(round(pct_25_3_loc, 2), scale = 100)) %>%
  sf::st_as_sf() %>%
  sf::st_transform(crs = sf::st_crs(3857))


```


```{r}

breaks <- chrt_dta %>%
  pull(pct_25_3_loc) %>%
  classIntervals(
    n = 5,
    style = "jenks"
  )

fig <- chrt_dta %>%
  mutate(
    val = cut(
      pct_25_3_loc,
      breaks$brks,
      labels = formatCutLabels(breaks$brks)
    )
  ) %>%
  sf::st_as_sf() %>%
  ggplot() +
  geom_sf(aes(fill = val)) +
  scale_fill_cori(
    palette = "ctg3gn",
  ) +
  labs(
    title = "Jenks",
    subtitle = "Percent of locations with 25/3 broadband service",
    caption = "Source: 2022 FCC estimates"
  ) +
  theme_cori_map() +
  theme(
    legend.text = element_text(margin = margin(r = 10)),
    legend.key.size = unit(12, "pt"), 
    legend.margin = margin(t = 5)
  ) +
  guides(fill = guide_legend(nrow = 1))

save_plot(fig, here::here("export/choropleth_jenks_co.png"), chart_height = 8)


```

```{r}

breaks <- chrt_dta %>%
  pull(pct_25_3_loc) %>%
  classIntervals(
    n = 5,
    style = "jenks"
  )

chrt_labels <- c(
    title = "Jenks",
    subtitle = "Percent of locations with 25/3 broadband service",
    caption = "Source: 2022 FCC estimates"
)

fig_jenks <- get_choropleth(chrt_dta, breaks, chrt_labels) +
  theme(
    legend.text = element_text(margin = margin(r = 10)),
    legend.key.size = unit(12, "pt"),
    legend.margin = margin(t = 5)
  ) +
  guides(fill = guide_legend(nrow = 1))

save_plot(fig_jenks, here::here("export/choropleth_jenks_co.png"), chart_height = 8)

```





