---
title: "cs-choropleth-co"
output: html_document
---

```{r}

library(dplyr)
library(cori.charts)
library(ggplot2)
library(scales)
library(classInt)

library(sysfonts)
library(showtext)

sysfonts::font_add_google("Lato")
font_add(
  "TT Hoves",
  regular = "TypeType - TT Hoves Regular.ttf",
  bold = "TypeType - TT Hoves Bold.ttf",
  italic = "TypeType - TT Hoves Italic.ttf",
  bolditalic = "TypeType - TT Hoves Bold Italic.ttf"
)
showtext_auto()
showtext_opts(dpi = 300)

here::i_am("R/cm-choropleth-co.Rmd")
source(here::here("R/utils.R"))

```


```{r}

# sum_var = "C24010_001"
acs_vars <- c(
  "cm_jobs" = "C24010_008",
  "cm_jobs" = "C24010_044"
)

chrt_dta <- tidycensus::get_acs(
    "county",
    variables = acs_vars,
    state = "08", # Colorado
    geometry = TRUE,
    summary_var = "C24010_001"
  ) %>%
  group_by(GEOID, geometry, NAME, summary_est) %>%
  summarise(
    cm_jobs = sum(estimate, na.rm = TRUE)
  ) %>%
  mutate(
    pct_cm = cm_jobs / summary_est
  ) %>%
  sf::st_as_sf() %>%
  sf::st_transform(crs = sf::st_crs(3857))
  

```


```{r}

breaks <- chrt_dta %>%
  pull(pct_cm) %>%
  classIntervals(
    n = 5,
    style = "jenks"
  )

chrt_labels <- list(
    title = "Jenks",
    subtitle = "Share of employment in computer and math occupations",
    caption = "Source: 2021 ACS 5-year estimates"
)

fig_jenks <- get_choropleth(chrt_dta, breaks, chrt_labels, value_col = "pct_cm") +
  theme(
    legend.key = element_rect(color = "dimgray", linewidth = 1),
    legend.text = element_text(margin = margin(r = 8)),
    legend.margin = margin(t = 5)
  ) +
  guides(fill = guide_legend(nrow = 1))

save_plot(fig_jenks, here::here("export/choropleth_jenks_co_cm_jobs.png"), chart_height = 8.4)

```


```{r}

# Make a distribution chart for Jenks

scale_dta <- chrt_dta %>%
  mutate(
    fill_var = cut(
      pct_cm,
      breaks$brks,
      labels = formatCutLabels(breaks$brks),
      include.lowest = TRUE
    )
  ) %>%
  sf::st_drop_geometry() %>%
  group_by(fill_var) %>%
  summarise(
    count = n()
  )

fig_jenks_dist <- ggplot(scale_dta, aes(x = fill_var, y = count, fill = fill_var)) +
  geom_col() +
 geom_text(
    aes(label = scales::number(count, accuracy = 1)),
    fontface = "bold",
    vjust = -.4,
    family = "Lato",
    size = 6
  ) +
  scale_x_discrete(
    expand = expansion(mult = c(0, 0))
  ) +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.1))
  ) +
  scale_fill_brewer(na.value = "#d0d2ce") + 
  labs(
    title = NULL,
    subtitle = NULL,
    x = NULL,
    y = NULL,
    caption = NULL
  ) +
  theme_cori_presentation() +
  theme(
    legend.position = "none",
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    axis.text.x = element_text(margin = margin(t = 4)),
    panel.grid.major.y = element_line(color = "#d0d2ce", linetype = "solid", linewidth = .25)
  )

save_plot(fig_jenks_dist, here::here("export/jenks_dist_cm_jobs_co.png"), add_logo = FALSE, chart_height = 4)

```

```{r}

breaks <- chrt_dta %>%
  pull(pct_cm) %>%
  classIntervals(
    n = 5,
    style = "equal"
  )

chrt_labels <- list(
    title = "Equal",
    subtitle = "Share of employment in computer and math occupations",
    caption = "Source: 2021 ACS 5-year estimates"
)

fig_equal <- get_choropleth(chrt_dta, breaks, chrt_labels, value_col = "pct_cm") +
  theme(
    legend.key = element_rect(color = "dimgray", linewidth = 1),
    legend.text = element_text(margin = margin(r = 8)),
    legend.margin = margin(t = 5)
  ) +
  guides(fill = guide_legend(nrow = 1))

save_plot(fig_equal, here::here("export/choropleth_equal_co_cm_jobs.png"), chart_height = 8.4)

```

```{r}

breaks <- chrt_dta %>%
  pull(pct_cm) %>%
  classIntervals(
    n = 5,
    style = "quantile"
  )

chrt_labels <- list(
    title = "Quantile",
    subtitle = "Share of employment in computer and math occupations",
    caption = "Source: 2021 ACS 5-year estimates"
)

fig_quantile <- get_choropleth(chrt_dta, breaks, chrt_labels, value_col = "pct_cm") +
  theme(
    legend.key = element_rect(color = "dimgray", linewidth = 1),
    legend.text = element_text(margin = margin(r = 8)),
    legend.margin = margin(t = 5)
  ) +
  guides(fill = guide_legend(nrow = 1))

save_plot(fig_quantile, here::here("export/choropleth_quantile_co_cm_jobs.png"), chart_height = 8.4)

```

```{r}

breaks <- chrt_dta %>%
  pull(pct_cm) %>%
  classIntervals(
    n = 5,
    style = "sd"
  )

chrt_labels <- list(
    title = "Standard deviation",
    subtitle = "Share of employment in computer and math occupations",
    caption = "Source: 2021 ACS 5-year estimates"
)

fig_sd <- get_choropleth(chrt_dta, breaks, chrt_labels, value_col = "pct_cm") +
  theme(
    legend.key = element_rect(color = "dimgray", linewidth = 1),
    legend.text = element_text(margin = margin(r = 8)),
    legend.margin = margin(t = 5)
  ) +
  guides(fill = guide_legend(nrow = 1))

save_plot(fig_sd, here::here("export/choropleth_sd_co_cm_jobs.png"), chart_height = 8.4)

```


```{r}

# Create a histogram
fig_dist <- ggplot(chrt_dta, aes(x = pct_cm)) +
  geom_histogram(binwidth = .01, fill = "#00835D", color = "black") +
  scale_x_continuous(
    labels = percent_format(scale = 100),
    expand = expansion(mult = c(0, 0))
  ) +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.2))
  ) +
  labs(
    title = "Distribution of computer and math\nemployment shares",
    subtitle = "For Colorado counties",
    x = NULL,
    y = NULL,
    caption = "Source: 2021 ACS 5-year estimates"
  ) + 
  theme_cori_presentation() +
  theme(
    panel.grid.major.y = element_line(color = "#d0d2ce", linetype = "solid", linewidth = .25)
  )
  
save_plot(fig_dist, here::here("export/hist_cm_jobs_co.png"))

```

