---
title: "cm-proportional-sym-co"
output: html_document
---

```{r}

library(dplyr)
library(cori.charts)
library(ggplot2)
library(scales)
library(classInt)
library(cartogram)

library(sysfonts)
library(showtext)

sysfonts::font_add_google("Lato")
font_add(
  "TT Hoves",
  regular = "TypeType - TT Hoves Regular.ttf",
  bold = "TypeType - TT Hoves Bold.ttf",
  italic = "TypeType - TT Hoves Italic.ttf",
  bolditalic = "TypeType - TT Hoves Bold Italic.ttf"
)
showtext_auto()
showtext_opts(dpi = 300)

here::i_am("R/cm-proportional-sym-co.Rmd")
source(here::here("R/utils.R"))

```


```{r}

acs_vars <- c(
  "cm_jobs" = "C24010_008",
  "cm_jobs" = "C24010_044"
)

chrt_dta <- tidycensus::get_acs(
    "county",
    variables = acs_vars,
    state = "08", # Colorado
    geometry = TRUE,
    summary_var = "C24010_001"
  ) %>%
  group_by(GEOID, geometry, NAME, summary_est) %>%
  summarise(
    cm_jobs = sum(estimate, na.rm = TRUE)
  ) %>%
  mutate(
    pct_cm = cm_jobs / summary_est
  ) %>%
  sf::st_as_sf() %>%
  sf::st_transform(crs = sf::st_crs(3857))
  

```


```{r}

# Centroid proportional symbol map

chrt_dta_carto <- chrt_dta %>%
  sf::st_transform(crs = 3857) %>%
  cartogram_dorling(weight = "cm_jobs", k = 1)

fig <- chrt_dta_carto %>%
  ggplot() +
  geom_sf(data = chrt_dta, color = "#d0d2ce", linewidth = 0.5, fill = NA) +
  geom_sf(aes(fill = pct_cm), color = "black", linewidth = 0.0, alpha = .75) +
  scale_fill_gradient2(
    low = "#f7fbff", high = "#08306b", na.value = "#d0d2ce",
    labels = scales::percent_format(scale = 100),
    limits = c(0, NA)
  ) +
  theme_cori_map_presentation() +
  theme(
    legend.key.width = unit(60, "pt"),
    legend.margin = margin(t = 5)
  ) +
  labs(
    title = "Centroids",
    subtitle = "Share employed in computer and math jobs, circles sized by total\ncomputer and math employment",
    caption = "Source: 2021 ACS 5-year estimates"
  )

save_plot(fig, here::here("export/proportional_sym_centroid_cm_jobs_co.png"), chart_height = 9.3)


```

```{r}

cenpop_dta <- readr::read_csv(here::here("data/US_county_cenpop_2020.csv"))

# Centers of Population proportional symbol map

chrt_dta_cenpop <- left_join(
    chrt_dta %>% sf::st_drop_geometry(),
    cenpop_dta,
    by = "GEOID"
  ) %>%
  sf::st_as_sf(
    crs = 4326,
    coords = c("LONGITUDE", "LATITUDE")
  )

fig2 <- ggplot() +
  geom_sf(data = chrt_dta, fill = NA, color = "#d0d2ce", linewidth = 0.5) +
  geom_sf(
    data = chrt_dta_cenpop,
    aes(
      color = `pct_cm`,
      size = `cm_jobs`
    ),
    alpha = 0.7,
    shape = 16,
    fill = "red"
  ) +
  scale_color_gradient2(
    low = "#f7fbff", high = "#08306b", na.value = "#d0d2ce",
    labels = scales::percent_format(scale = 100)
  ) +
  scale_size_continuous(
    range = c(0, 22),
    guide = "none"
  ) +
  theme_cori_map_presentation() +
  theme(
    legend.key.width = unit(60, "pt"),
    legend.margin = margin(t = 5)
  ) +
  labs(
    title = "Centers of population",
    subtitle = "Share employed in computer and math jobs, circles sized by total\ncomputer and math employment",
    caption = "Source: 2021 ACS 5-year estimates"
  )

save_plot(fig2, here::here("export/proportional_sym_cenpop_cm_jobs_co.png"), chart_height = 9.3)

```
