---
title: "data-normalization"
output: html_document
---

```{r}

library(dplyr)
library(cori.charts)
library(ggplot2)
library(scales)
library(classInt)

library(sysfonts)
library(showtext)

sysfonts::font_add_google("Lato")
font_add(
  "TT Hoves",
  regular = "TypeType - TT Hoves Regular.ttf",
  bold = "TypeType - TT Hoves Bold.ttf",
  italic = "TypeType - TT Hoves Italic.ttf",
  bolditalic = "TypeType - TT Hoves Bold Italic.ttf"
)
showtext_auto()
showtext_opts(dpi = 300)

here::i_am("R/data-normalization.Rmd")
source(here::here("R/utils.R"))

```


```{r}

# Load broadband data to use in map examples
bb_tr <- get_bb_tr(geo = TRUE, st = "08")

```


```{r}

# Convert to mercator projection
chrt_dta <- bb_tr %>%
  sf::st_as_sf() %>%
  sf::st_transform(crs = sf::st_crs(3857))

```

```{r}

fig_normalized <- chrt_dta %>%
  ggplot() +
  geom_sf(aes(fill = pct_25_3_loc), color = "#d0d2ce", linewidth = 0.01) +
 scale_fill_gradient2(
    low = "#FCF2EE", mid = "#BA578C", midpoint = 0.5, high = "#211448", 
    na.value = "#d0d2ce",
    labels = scales::percent_format(scale = 100)
  ) +
  theme_cori_map_presentation() +
  theme(
    legend.key.width = unit(60, "pt"),
    legend.margin = margin(t = 5)
  ) +
  labs(
    title = "Normalized",
    subtitle = "Percent of locations with 25/3 broadband service",
    caption = "Source: 2022 FCC estimates"
  )

save_plot(fig_normalized, here::here("export/choropleth_normalized.png"), chart_height = 8.4)

```


```{r}

co_border <- tigris::states(cb = TRUE, year = 2021) %>%
  filter(STATEFP == "08")
  
fig_unnormalized <- chrt_dta %>%
  ggplot() +
  geom_sf(data = co_border, fill = NA, color = "dimgray", linewidth = 0.5) +
  geom_sf(aes(fill = cnt_25_3), color = "dimgray", linewidth = 0.025) +
 scale_fill_gradient2(
    low = "#FCF2EE", 
    mid = "#BA578C", 
    midpoint = max(chrt_dta$cnt_25_3, na.rm = TRUE)/2,
    high = "#211448", 
    na.value = "#d0d2ce",
    labels = scales::number_format(scale = 1, scale_cut = scales::cut_short_scale())
  ) +
  theme_cori_map_presentation() +
  theme(
    legend.key.width = unit(60, "pt"),
    legend.margin = margin(t = 5)
  ) +
  labs(
    title = "Unnormalized",
    subtitle = "Number of locations with 25/3 broadband service",
    caption = "Source: 2022 FCC estimates"
  )

save_plot(fig_unnormalized, here::here("export/choropleth_unnormalized.png"), chart_height = 8.4)

```
