---
title: "leaflet-maps"
output: html_document
---

```{r}

library(dplyr)
library(leaflet)
library(sf.dotdensity)

here::i_am("R/leaflet-maps.Rmd")
source(here::here("R/utils.R"))

```


```{r}

acs_vars <- c(
  "cm_jobs" = "C24010_008",
  "cm_jobs" = "C24010_044"
)

# Calculate percent employment in computer and
# math employment using tidycensus
acs_dta <- tidycensus::get_acs(
    "county",
    variables = acs_vars,
    geometry = TRUE,
    summary_var = "C24010_001"
  ) %>%
  group_by(GEOID, geometry, NAME, summary_est) %>%
  summarise(
    cm_jobs = sum(estimate, na.rm = TRUE)
  ) %>%
  mutate(
    pct_cm = cm_jobs / summary_est,
    geoid_st = stringr::str_sub(GEOID, 1, 2)
  ) %>%
  # Remove territories, Hawaii, and Alaska
  filter(!geoid_st %in% c("02", "15")) %>%
  filter(geoid_st <= "56")
  
```



```{r}

# Interactive choropleth map
map_dta <- acs_dta %>%
  sf::st_as_sf() %>%
  sf::st_transform(crs = sf::st_crs("+proj=longlat +datum=WGS84"))

leaflet_map <- leaflet(map_dta) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~colorNumeric(palette = c("#E5F9F3", "#3F8EE6", "#280050"), domain = map_dta$pct_cm)(pct_cm),
    color = ~colorNumeric(palette = c("#E5F9F3", "#3F8EE6", "#280050"), domain = map_dta$pct_cm)(pct_cm),
    fillOpacity = 0.75,
    weight = 1,
    highlight = highlightOptions(
      color = "orange",
      weight = 2,
      bringToFront = TRUE
    ),
    label = ~paste0("<b><i>", NAME, "<i></b><br>", "Percent computer and math occupations: <b>", scales::percent(pct_cm, scale = 100, accuracy = .1), "</b>") %>%
      lapply(htmltools::HTML)
  )


```


```{r}

# Interactive dot density map

bb_tr <- get_bb_tr(geo = TRUE, st = "08")

unserved_dots <- bb_tr %>%
  mutate(
    cnt_unserved = cnt_total_locations - cnt_25_3
  ) %>%
  filter(!is.na(cnt_unserved)) %>%
  filter(cnt_unserved > 0) %>%
  sf::st_as_sf() %>%
  sf::st_transform(crs = 4326) %>%
  sf.dotdensity::calc_dots(
    "cnt_unserved",
    10
  ) %>%
  mutate(
    service_level = "Unserved"
  )

```


```{r}

leaflet_map <- leaflet(unserved_dots) %>%
  addTiles() %>%
  addCircleMarkers(
    lng = ~lon,
    lat = ~lat,
    color = "#26535C",
    fillColor = "#26535C",
    radius = 2.5,
    fillOpacity = 0.6
  )

leaflet_map

```






